version: "2"
linters:
  enable:
    - copyloopvar
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocyclo:
      min-complexity: 15
formatters:
  enable:
    - gofmt
    - goimports
